language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
install:
    - phpenv config-rm xdebug.ini
    - pecl install uopz
    - if [[ $TRAVIS_PHP_VERSION == "7.4" ]]; then echo "opcache.enable=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
    - composer install
before_script:
    - export PATH=vendor/bin:$PATH
script:
    - phing sniff
    - phing unit-tests
