<?php
/* utf8-marker = äöüß */
$cf['security']['password']="test";
$cf['security']['type']="page";
$cf['site']['template']="cmsimplexh";
$cf['language']['default']="en";
$cf['meta']['robots']="index, follow";
$cf['meta']['author']="";
$cf['meta']['publisher']="";
$cf['locator']['show_homepage']="true";
$cf['folders']['userfiles']="userfiles/";
$cf['folders']['downloads']="downloads/";
$cf['folders']['images']="images/";
$cf['folders']['media']="downloads/";
$cf['backup']['numberoffiles']="10";
$cf['show_hidden']['pages_toc']="";
$cf['show_hidden']['pages_search']="";
$cf['show_hidden']['pages_sitemap']="";
$cf['show_hidden']['path_locator']="";
$cf['images']['maxsize']="150000";
$cf['downloads']['maxsize']="1000000";
$cf['editor']['external']="tinymce";
$cf['editor']['height']="600";
$cf['filebrowser']['external']="";
$cf['pagemanager']['external']="";
$cf['menu']['color']="000000";
$cf['menu']['highlightcolor']="808080";
$cf['menu']['levels']="3";
$cf['menu']['levelcatch']="10";
$cf['menu']['sdoc']="parents";
$cf['menu']['legal']="CMSimple Legal Notices";
$cf['uri']['seperator']=":";
$cf['uri']['length']="200";
$cf['xhtml']['endtags']="";
$cf['xhtml']['amp']="true";
$cf['scripting']['regexp']="\#CMSimple (.*?)\#";
$cf['editmenu']['scroll']="";
?>