<?php

$mcf['security']['password']="password";
$mcf['security']['secret']="random";
$mcf['security']['frame_options']="enum:DENY,SAMEORIGIN,";
$mcf['site']['template']="function:XH_templates";
$mcf['language']['default']="function:XH_availableLocalizations";
$mcf['language']['2nd_lang_names']="hidden";
$mcf['locator']['show_homepage']="bool";
$mcf['folders']['content']="hidden";
$mcf['show_hidden']['pages_toc']="bool";
$mcf['show_hidden']['pages_search']="bool";
$mcf['show_hidden']['pages_sitemap']="bool";
$mcf['show_hidden']['path_locator']="bool";
$mcf['editor']['external']="xfunction:XH_registeredEditorPlugins";
$mcf['filebrowser']['external']="xfunction:XH_registeredFilebrowserPlugins";
$mcf['pagemanager']['external']="xfunction:XH_registeredPagemanagerPlugins";
$mcf['mailform']['captcha']="bool";
$mcf['mailform']['lf_only']="hidden";
$mcf['menu']['color']="hidden";
$mcf['menu']['highlightcolor']="hidden";
$mcf['menu']['levels']="enum:1,2,3,4,5,6";
$mcf['menu']['levelcatch']="hidden";
$mcf['menu']['legal']="hidden";
$mcf['menu']['sdoc']="enum:,parent";
$mcf['uri']['length']="hidden";
$mcf['xhtml']['endtags']="bool";
$mcf['xhtml']['amp']="hidden";
$mcf['editmenu']['scroll']="bool";
$mcf['editmenu']['external']="xfunction:XH_registeredEditmenuPlugins";
?>
